using Sportiva.Contracts.TimeSlots;

namespace Sportiva.Services;

public interface ITimeSlotService
{
    // ── Read ──────────────────────────────────────────────────────────────
    Task<Result<IReadOnlyList<TimeSlotResponse>>> GetTimeSlotsAsync(
        string courtId, DateOnly? date = null, bool? available = null, CancellationToken ct = default);

    Task<Result<TimeSlotResponse>> GetTimeSlotAsync(
        string courtId, string slotId, CancellationToken ct = default);

    // ── Owner control (block/unblock slots already generated by the system) ─
    Task<Result<IReadOnlyList<TimeSlotResponse>>> SetTimeSlotsAvailabilityAsync(
        string userId, string courtId, IReadOnlyList<string> slotIds, bool isActive,
        CancellationToken ct = default);

    // ── System-triggered generation (called by Hangfire job) ───────────────
    Task<Result<int>> GenerateWeeklyTimeSlotsForCourtAsync(
        string courtId, CancellationToken ct = default);
}